---
- name: Allow login using password for multiple users
  hosts: training
  become: true

  tasks:
    - name: Create ssh password config file
      copy:
        dest: "/etc/ssh/sshd_config.d/10-password-login-for-special-users.conf"
        content: |
          {% for user in users %}
          Match User {{ user.username }}
            PasswordAuthentication yes
          {% endfor %}

    - name: Restart the sshd service
      service:
        name: ssh
        state: restarted

